In [4]:
import torch

# A Tensor is a sort of array
x = torch.Tensor([5,3])
y = torch.Tensor([2,1])

# We multiplied an array
print(x*y)


tensor([10.,  3.])


In [3]:
x = torch.zeros([2,5])
print(x)
x.shape

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


torch.Size([2, 5])

In [7]:
y = torch.rand([2,5])
y

tensor([[0.9436, 0.3278, 0.6763, 0.9403, 0.0812],
        [0.8848, 0.3504, 0.9797, 0.4674, 0.0661]])

In [8]:
# So for example we want to put this "image" of [2,5] pixels in to a NN. We have to flatten it first!
# By flattening we mean that we change the matrix that we originally had of size [n,m] to a [1,n*m] matrix
# For this we use the .view([1,n*m]) function
y.view([1,10])

tensor([[0.9436, 0.3278, 0.6763, 0.9403, 0.0812, 0.8848, 0.3504, 0.9797, 0.4674,
         0.0661]])

In [9]:
# The view function does not change the original matrix, it does instead return a reshaped one
y

tensor([[0.9436, 0.3278, 0.6763, 0.9403, 0.0812],
        [0.8848, 0.3504, 0.9797, 0.4674, 0.0661]])

In [10]:
# Meaning we have to save it in to a variable ourselves
newY = y.view([1,10])
newY

tensor([[0.9436, 0.3278, 0.6763, 0.9403, 0.0812, 0.8848, 0.3504, 0.9797, 0.4674,
         0.0661]])